### ISSUE TITLE
Please allow me to write to the repository :-)

### ISSUE THREAD

**Issue by aborel** [msbr0815/MARCXML-Infoscience#1]
J'ai créé une branche locale pour mon code, j'aimerais la pousser sur Github.

**Comment by aborel** [comment]
Merci!

**Comment by msbr0815** [comment]
Elles sont très élégantes, tes mises à jour du script ! Merci beaucoup 😊

De : aborel <notifications@github.com>
Envoyé : lundi, 17 février 2020 16:14
À : msbr0815/MARCXML-Infoscience <MARCXML-Infoscience@noreply.github.com>
Cc : Subscribed <subscribed@noreply.github.com>
Objet : Re: [msbr0815/MARCXML-Infoscience] Please allow me to write to the repository :-) (#1)


Closed #1<https://github.com/msbr0815/MARCXML-Infoscience/issues/1>.
